### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by ozzym1096** [ozzym1096/ecomm-demo#7]
Currently, the site looks good enough on mobile portrait and landscape. Now it needs to look good on tablet and desktop sizes.

**Comment by chinmaym07** [comment]
Hey @ozzym1096  Can I try this .?

**Comment by ozzym1096** [comment]
Sure! The only thing is that the project is set up to fetch products from a PostgreSQL database and the images are loaded from a Cloudinary account.

I am working on creating a script to set up the database automatically, but you can set it up yourself for now (You could also just create a JSON file with dummy data and load that instead).

**Comment by chinmaym07** [comment]
I have created a JSON dummy file following the same structure as this.

	 id: string,
	 name: string,
	 department: string,
	 price: 
	 materials: string[],
	 description: string,
	 image: string

I was facing problem in loading it.Please help.!!

**Comment by ozzym1096** [comment]
For now you can load the data in the products page by going to `src/routes/products/index.svelte` and replacing everything in the `preload` function with:
```
const response = await this.fetch("path/to/dummy/data.json");
const data = response.json();
return {data: products};
```
And in `src/components/ProductCard.svelte`, just edit the img element href to use your own images.
